// Caligo Pt.2 - 판매처 · 배급사 데이터
// 자동 생성 - 수동 편집하거나 admin.html에서 관리하세요
// Last updated: 2026-04-13

var DISTRIBUTORS = [
  {
    "id": "dcs1774546040116",
    "name": "공구플랫폼"
  },
  {
    "id": "dcs1774619306510",
    "name": "디어마이뮤즈"
  },
  {
    "id": "d2",
    "name": "메이크스타"
  },
  {
    "id": "d3",
    "name": "무신사"
  },
  {
    "id": "dcs1774619302089",
    "name": "버프즈"
  },
  {
    "id": "dcs1774619310313",
    "name": "비트로드"
  },
  {
    "id": "d8",
    "name": "애니메이트"
  },
  {
    "id": "d5",
    "name": "영풍문고 / MusicArt"
  },
  {
    "id": "d4",
    "name": "올리브영"
  },
  {
    "id": "dcs1774619329527",
    "name": "케타포"
  },
  {
    "id": "dcs1774544809341",
    "name": "훗타운"
  },
  {
    "id": "d9",
    "name": "Hello82"
  },
  {
    "id": "d7",
    "name": "HMV Japan"
  },
  {
    "id": "d10",
    "name": "TME (腾讯音乐)"
  },
  {
    "id": "d6",
    "name": "Tower Records Japan"
  },
  {
    "id": "dcs1774543391747",
    "name": "VLASTSHOP"
  },
  {
    "id": "dcs1774619738077",
    "name": "WEVERSE"
  },
  {
    "id": "d11",
    "name": "Will Music Taiwan"
  },
  {
    "id": "dcs1775249000000",
    "name": "사운드웨이브"
  },
  {
    "id": "dcs1774663794920",
    "name": "뮤직플랜트"
  },
  {
    "id": "dcs1775049442175",
    "name": "이즈위 (一直娱)"
  },
  {
    "id": "dcs1775566277516",
    "name": "Universal JP"
  },
  {
    "id": "dcs1776084976682",
    "name": "위드뮤"
  },
  {
    "id": "dcs1776085087300",
    "name": "Youtube"
  }
];

var STORES = [
  {
    "name": "길보드 (ASTERUM 433-10)",
    "distId": "",
    "country": "KR",
    "unpoPerk": "POCAALBUM",
    "priceMode": "country",
    "customPrices": {},
    "purchaseStart": "2026-04-20T15:00",
    "purchaseEnd": "2026-04-20T23:00",
    "purchaseEndTxt": "",
    "offlineStart": "2026-04-20",
    "offlineEnd": "2026-04-20",
    "offlineNote": "모든 버전 구매시 A2T DRAW (십카페 럭드) 와 동일한 포카 중 랜덤 1종 증정\n럭드 포토카드중 친필사인 포토카드 랜덤 제공",
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://caligopt2popup.oopy.io/32d4cacd-15c9-80d4-91e3-e505275bb65c",
    "custom": true,
    "id": "cs1774546479074",
    "defDeliveryDate": "",
    "offlineHours": "15:00 - 23:00",
    "offlineAddress": "서대문구 연희로11가길 48-23",
    "offlineLuckyDraw": true,
    "videocall": false,
    "memo": ""
  },
  {
    "name": "더현대서울",
    "distId": "",
    "country": "KR",
    "unpoPerk": "POCAALBUM",
    "priceMode": "country",
    "customPrices": {},
    "purchaseStart": "",
    "purchaseEnd": "",
    "purchaseEndTxt": "",
    "offlineStart": "2026-04-14",
    "offlineEnd": "2026-04-19",
    "offlineNote": "https://caligopt2popup.oopy.io/32d4cacd-15c9-80e1-b7b5-d07592ac0481\n모든 버전 구매시 더현대럭키드로우 포토카드 5종중 랜덤 증정",
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://caligopt2popup.oopy.io/32d4cacd-15c9-80e1-b7b5-d07592ac0481",
    "custom": true,
    "id": "cs1774546314667",
    "defDeliveryDate": "",
    "offlineHours": "(화-목) 10:30 - 20:00 ; (금-일) 10:30 - 20:30",
    "offlineAddress": "더현대서울 5F",
    "offlineLuckyDraw": true,
    "videocall": false,
    "memo": ""
  },
  {
    "id": "s3",
    "distId": "d2",
    "name": "메이크스타",
    "country": "KR",
    "priceMode": "country",
    "customPrices": {},
    "unpoPerk": "POCAALBUM",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-04-20T19:59",
    "purchaseEndTxt": "",
    "offlineStart": "2026-04-14",
    "offlineEnd": "2026-04-20",
    "offlineNote": "[강남] MAKESTAR SPACE GANGNAM",
    "url": "https://www.makestar.com/product/16439",
    "defDomShip": 3000,
    "defOvsShip": 0,
    "custom": true,
    "offlineHours": "매일 12:00~20:00",
    "offlineAddress": "서울시 학동로23길 29 B1",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": "POCAALBUM ver. 구매 시 미공개 포토카드 1매 랜덤 증정\n\n*총 5종, 앨범 1매 당 랜덤 1매\n*한 주문 건에서 앨범 2매 이상 구매 시 포토카드 중복없이 증정\n*본 이벤트에서 제공하는 포토카드는 온라인/오프라인 동일한 초상입니다."
  },
  {
    "id": "s4",
    "distId": "d3",
    "name": "무신사 (1차)",
    "country": "KR",
    "priceMode": "country",
    "customPrices": {},
    "unpoPerk": "ID_PASS",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-04-13T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "url": "https://www.musinsa.com/search/goods?keyword=PLAVE+4th+Mini+Album+Caligo+Pt.2",
    "defDomShip": 0,
    "defOvsShip": 0,
    "custom": true,
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": "구매 수량에 맞춰 1:1 랜덤 증정\n온라인: 한 주문번호 내 앨범 2장 구매 시 중복없이 증정\n오프라인 (무신사 성수): 앨범 2장 이상 구매 시 중복없이 증정"
  },
  {
    "id": "s5",
    "distId": "d3",
    "name": "무신사 (2차)",
    "country": "KR",
    "priceMode": "country",
    "customPrices": {},
    "unpoPerk": "ID_PASS",
    "purchaseStart": "2026-04-14T11:00",
    "purchaseEnd": "2026-04-20T23:00",
    "purchaseEndTxt": "",
    "offlineStart": "2026-04-14",
    "offlineEnd": "2026-04-20",
    "offlineNote": "무신사 온라인: ASTERUM 433-10 (십카페럭드)와 동일\n무신사 스토어 성수 (연무장길 83 1F) - 무신사 1차럭드와 동일\n무신사 스토어 명동 (명동길 13) - ASTERUM 433-10 (십카페럭드)와 동일",
    "url": "https://www.musinsa.com/search/goods?keyword=PLAVE+4th+Mini+Album+Caligo+Pt.2&gf=A&keywordType=keyword",
    "defDomShip": 0,
    "defOvsShip": 0,
    "custom": true,
    "offlineHours": "11:00~10:00 ",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": "ID PASS 구매 시 미공포 (온오프동일)\n구매수량에 맞춰 1:1 랜덤증정\n온라인: 한 주문번호 내 앨범 2장 이상 구매 시 중복없이 증정\n오프라인: 앨범 2장 이상 구매 시 중복없이 증정"
  },
  {
    "id": "s10",
    "distId": "d8",
    "name": "애니메이트",
    "country": "KR",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": null,
      "POCAALBUM": null,
      "ID_PASS": 14900,
      "INVENTORY": null
    },
    "unpoPerk": "ID_PASS",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-04-08T23:59",
    "purchaseEndTxt": "특전 소진시까지",
    "offlineStart": "2026-04-14",
    "offlineEnd": "2026-05-31",
    "offlineNote": "그라떼 7천원 / 아이싱쿠키 6,500원\n랜덤아크릴코스터 7,500원",
    "url": "https://animate-onlineshop.co.kr/goods/goods_view.php?goodsNo=1000089045",
    "defDomShip": 0,
    "defOvsShip": 0,
    "custom": true,
    "offlineHours": "",
    "offlineAddress": "애니메이트 홍대점, 잠실롯데점, 부산점",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": "특전: 포토카드 (전 5종 1세트 증정)【미공개 포토카드】\n※특전은 소진 시 종료됩니다.\n포토북, 인벤, 포카앨범 구매 시 특전엽서 1매 증정 (일본애니메이트샵)"
  },
  {
    "id": "s7",
    "distId": "d5",
    "name": "영풍문고 (뮤직아트)",
    "country": "KR",
    "priceMode": "country",
    "customPrices": {},
    "unpoPerk": "POCAALBUM",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-04-20T22:00",
    "purchaseEndTxt": "",
    "offlineStart": "2026-04-14",
    "offlineEnd": "2026-04-20",
    "offlineNote": "📍 the stage by Musicart (청계천로 41 영풍빌딩 B2)\n📍 영풍문고 여의도 IFC몰점 (국제금융로 10 L2)\n📍 영풍문고 홍대점 (양화로 161 케이스퀘어 B2)",
    "url": "http://musicart.kr/shop/shopdetail.html?branduid=3530779",
    "defDomShip": 3000,
    "defOvsShip": 0,
    "custom": true,
    "offlineHours": "10:00 - 22:00",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": "POCAALBUM 구매 시 미공포 (온오프동일)\n한 주문 번호에 2장 이상 앨범 구매 시 특전 포토카드는 중복 없이 증정됩니다."
  },
  {
    "id": "s6",
    "distId": "d4",
    "name": "올리브영",
    "country": "KR",
    "priceMode": "country",
    "customPrices": {},
    "unpoPerk": "ID_PASS",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-04-20T22:00",
    "purchaseEndTxt": "",
    "offlineStart": "2026-04-14",
    "offlineEnd": "2026-04-20",
    "offlineNote": "📍 올리브영N 성수 (연무장7길 13) 10:00~22:00\n📍 올리브영 홍대놀이터점 (와우산로21길 29) 10:00~22:00",
    "url": "https://www.oliveyoung.co.kr/store/planshop/getPlanShopDetail.do?dispCatNo=500000100018171",
    "defDomShip": 0,
    "defOvsShip": 0,
    "custom": true,
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": "ID PASS 구매 시 미공포 (온오프동일)"
  },
  {
    "id": "s8",
    "distId": "d6",
    "name": "타워레코드",
    "country": "JP",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 3590,
      "POCAALBUM": 1890,
      "ID_PASS": 2420,
      "INVENTORY": 3490
    },
    "unpoPerk": "ID_PASS",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "",
    "purchaseEndTxt": "특전 소진시까지",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "url": "https://tower.jp/search/item/plave%20caligo%20pt%EF%BC%8E2",
    "defDomShip": 0,
    "defOvsShip": 1210,
    "custom": true,
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": ""
  },
  {
    "name": "[음총] 타워레코드 (1차)",
    "distId": "dcs1774546040116",
    "country": "KR",
    "unpoPerk": "ID_PASS",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": null,
      "POCAALBUM": null,
      "ID_PASS": 24410,
      "INVENTORY": null
    },
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-03-29T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://x.com/Plave_Album/status/2036341423856034026?s=20",
    "custom": true,
    "id": "cs1774546219159",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "2026-05-01",
    "videocall": false,
    "memo": "출고 일정 : 05월 초 ~ 05월 중 예상"
  },
  {
    "id": "s11",
    "distId": "d9",
    "name": "Hello82 (예판)",
    "country": "US",
    "priceMode": "country",
    "customPrices": {},
    "unpoPerk": "ID_PASS",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-04-17T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "url": "https://hello82.com/search?q=plave&options%5Bprefix%5D=last",
    "defDomShip": 0,
    "defOvsShip": 0,
    "custom": true,
    "defDeliveryDate": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "videocall": false,
    "memo": "\"BITE\" ver"
  },
  {
    "id": "s12",
    "distId": "d9",
    "name": "Hello82 (팝업)",
    "country": "US",
    "priceMode": "country",
    "customPrices": {},
    "unpoPerk": "ID_PASS",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-04-17T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "url": "https://hello82.com/search?q=plave&options%5Bprefix%5D=last",
    "defDomShip": 0,
    "defOvsShip": 0,
    "custom": true,
    "defDeliveryDate": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "videocall": false,
    "memo": "\"LOOKUP\" ver"
  },
  {
    "id": "s9",
    "distId": "d7",
    "name": "HMV",
    "country": "JP",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 4070,
      "POCAALBUM": 1979,
      "ID_PASS": 2420,
      "INVENTORY": 3740
    },
    "unpoPerk": "ID_PASS",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "",
    "purchaseEndTxt": "특전 소진시까지",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "url": "https://www.hmv.co.jp/en/news/article/260317125/",
    "defDomShip": 0,
    "defOvsShip": 330,
    "custom": true,
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": "인벤토리를 제외하고 세트판매하지않음"
  },
  {
    "name": "HMV (1차)",
    "distId": "dcs1774546040116",
    "country": "KR",
    "unpoPerk": "ID_PASS",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": null,
      "POCAALBUM": null,
      "ID_PASS": 24412,
      "INVENTORY": null
    },
    "purchaseStart": "2026-03-24T02:28",
    "purchaseEnd": "2026-03-29T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://x.com/Plave_Album/status/2036341423856034026?s=20",
    "custom": true,
    "id": "cs1774546033455",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": ""
  },
  {
    "id": "s13",
    "distId": "d10",
    "name": "TME",
    "country": "CN",
    "priceMode": "country",
    "customPrices": {},
    "unpoPerk": "PHOTOBOOK",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-04-20T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "url": "https://i2.y.qq.com/n3/cm/pages/putao/product_detail/index.html?productID=1205354113456059",
    "defDomShip": 0,
    "defOvsShip": 70,
    "custom": true,
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": "(5种随机1种，购买5张凑套)\n→ 5종 중 랜덤 1종 / 5장 구매 시 한 세트 완성"
  },
  {
    "name": "TME",
    "distId": "dcs1774544809341",
    "country": "KR",
    "unpoPerk": "PHOTOBOOK",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 22683.6,
      "POCAALBUM": null,
      "ID_PASS": null,
      "INVENTORY": null
    },
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-03-27T08:00",
    "purchaseEndTxt": "특전 소진시까지",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://x.com/Plave_Album/status/2036611347409231996?s=20",
    "custom": true,
    "id": "cs1774545021788",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": "(5种随机1种，购买5张凑套)\n→ 5종 중 랜덤 1종 / 5장 구매 시 한 세트 완성"
  },
  {
    "id": "s1",
    "distId": "dcs1774543391747",
    "name": "VLAST SHOP",
    "country": "KR",
    "priceMode": "country",
    "customPrices": {},
    "unpoPerk": "PHOTOBOOK",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-03-27T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "url": "https://vlastshop.com/product/search.html?banner_action=&keyword=PLAVE+Caligo+Pt.2",
    "defDomShip": 0,
    "defOvsShip": 0,
    "custom": true,
    "defDeliveryDate": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "videocall": true,
    "memo": ""
  },
  {
    "id": "s2",
    "distId": "dcs1774619738077",
    "name": "Weverse Shop",
    "country": "KR",
    "priceMode": "country",
    "customPrices": {},
    "unpoPerk": "POCAALBUM",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-04-13T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "url": "https://shop.weverse.io/ko/shop/KRW/artists/167/categories/3719",
    "defDomShip": 3000,
    "defOvsShip": 0,
    "custom": true,
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false
  },
  {
    "id": "s14",
    "distId": "d11",
    "name": "Will Music",
    "country": "TW",
    "priceMode": "country",
    "customPrices": {},
    "unpoPerk": "POCAALBUM",
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-04-20T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "url": "https://www.willmusic.com.tw/SalePage/Index/11651010",
    "defDomShip": 0,
    "defOvsShip": 0,
    "custom": true,
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "",
    "videocall": false,
    "memo": ""
  },
  {
    "name": "Will Music",
    "distId": "dcs1774544809341",
    "country": "KR",
    "unpoPerk": "POCAALBUM",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": null,
      "POCAALBUM": 10506,
      "ID_PASS": null,
      "INVENTORY": null
    },
    "purchaseStart": "2026-03-24T11:00",
    "purchaseEnd": "2026-04-13T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://x.com/Plave_Album/status/2036611347409231996?s=20",
    "custom": true,
    "id": "cs1774545187345",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false
  },
  {
    "name": "[음총] 디어마이뮤즈",
    "distId": "dcs1774619306510",
    "country": "KR",
    "unpoPerk": "",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 16500,
      "POCAALBUM": 6900,
      "ID_PASS": 1200,
      "INVENTORY": 14200
    },
    "purchaseStart": "2026-03-24T02:25",
    "purchaseEnd": "2026-04-14T19:00",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://x.com/Plave_Album/status/2036340525821993312?s=20",
    "custom": true,
    "id": "cs1774545937612",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "2026-04-15",
    "videocall": false,
    "memo": "할인/초동 반영100%/무특전/전광판 광고/7만 무배; \n특전/혜택: 디마뮤 사옥 전광판 광고 (4/14 - 4/20)"
  },
  {
    "name": "[음총] 버프즈",
    "distId": "dcs1774619302089",
    "country": "KR",
    "unpoPerk": "",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 19000,
      "POCAALBUM": 7790,
      "ID_PASS": 14155,
      "INVENTORY": 16245
    },
    "purchaseStart": "2026-03-24T02:23",
    "purchaseEnd": "2026-04-03T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://x.com/Plave_Album/status/2036291046146265331?s=20",
    "custom": true,
    "id": "cs1774545824537",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "2026-04-14",
    "videocall": false,
    "memo": "할인/초동 반영100%/무특전/가격 상관 없이 무조건 무료배송\n앨범 발매 당일 발송 보장\n*버프즈 신규 회원 혜택\n- 총 1만원 즉시 할인 (3만원 이상 구매 시 3천원 + 7만원 이상 구매 시 7천원)\n- 첫 구매 완료 시 10% 적립금 쿠폰 페이백(최대 5천원)"
  },
  {
    "name": "[음총] 비트로드",
    "distId": "dcs1774619310313",
    "country": "KR",
    "unpoPerk": "",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 16500,
      "POCAALBUM": 6900,
      "ID_PASS": 12400,
      "INVENTORY": 14200
    },
    "purchaseStart": "2026-03-24T02:21",
    "purchaseEnd": "2026-04-12T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://x.com/Plave_Album/status/2036292541986001367?s=20",
    "custom": true,
    "id": "cs1774545708995",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "2026-04-14",
    "videocall": false,
    "memo": "앨범 발매 당일부터 순차 발송 예쌍\n3만원 이상 무료 배송\n현재 최저가"
  },
  {
    "name": "[음총] 케타포",
    "distId": "dcs1774619329527",
    "country": "KR",
    "unpoPerk": "",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 16700,
      "POCAALBUM": 7000,
      "ID_PASS": 12500,
      "INVENTORY": 14300
    },
    "purchaseStart": "2026-03-24T02:18",
    "purchaseEnd": "2026-04-14T17:00",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineNote": "",
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://kr.ktown4u.com/eventinfo?eve_no=44113596&biz_no=967",
    "custom": true,
    "id": "cs1774545544751",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineLuckyDraw": false,
    "defDeliveryDate": "2026-04-15",
    "videocall": false,
    "memo": "3만 원 이상 구매 시 무료배송 (3만원 미만 3,000원)"
  },
  {
    "name": "사운드웨이브",
    "distId": "dcs1775249000000",
    "country": "KR",
    "unpoPerk": "INVENTORY",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": null,
      "POCAALBUM": null,
      "ID_PASS": null,
      "INVENTORY": 17100
    },
    "purchaseStart": "2026-04-05T11:00",
    "purchaseEnd": "2026-04-07T23:59",
    "purchaseEndTxt": "특전 소진시까지",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://www.soundwavemusic.co.kr",
    "memo": "Inventory 구매 시 미공포 5종 중 랜덤 1종 증정\n영상통화 이벤트 진행",
    "custom": true,
    "id": "cs1775249000001",
    "defDeliveryDate": "",
    "videocall": true
  },
  {
    "name": "뮤직플랜트",
    "distId": "dcs1774663794920",
    "country": "KR",
    "unpoPerk": "INVENTORY",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": null,
      "POCAALBUM": null,
      "ID_PASS": null,
      "INVENTORY": 17100
    },
    "purchaseStart": "2026-03-28T11:00",
    "purchaseEnd": "2026-03-31T23:59",
    "purchaseEndTxt": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://www.musicplant.co.kr/board/?db=gallery_1&no=1320&mari_mode=view%40view&cate=17&page=1&search=&search_str=&temp=",
    "memo": "응모 기간 (~3/31) 내 뮤직플랜트 온라인몰에서 Inventory 상품 구매고객중 50명 추첨하여 사인포카 증정\n영통: 2026년 4월 26일 / 시간 추후 안내",
    "custom": true,
    "id": "cs1774664589091",
    "defDeliveryDate": "",
    "videocall": true
  },
  {
    "name": "뮤직플랜트",
    "distId": "dcs1774663794920",
    "country": "KR",
    "unpoPerk": "",
    "priceMode": "country",
    "customPrices": {},
    "purchaseStart": "2026-03-28T11:00",
    "purchaseEnd": "2026-04-14T23:59",
    "purchaseEndTxt": "",
    "defDeliveryDate": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://www.musicplant.co.kr/shop/search_result.php?search_str=caligo&x=0&y=0",
    "videocall": false,
    "memo": "",
    "custom": true,
    "id": "cs1774700960047"
  },
  {
    "name": "[음총] 타워레코드 (2차)",
    "distId": "dcs1774546040116",
    "country": "KR",
    "unpoPerk": "ID_PASS",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": null,
      "POCAALBUM": null,
      "ID_PASS": 24410,
      "INVENTORY": null
    },
    "purchaseStart": "2026-03-30T11:00",
    "purchaseEnd": "2026-04-07T18:00",
    "purchaseEndTxt": "",
    "defDeliveryDate": "2026-05-15",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://09platform.com/surl/P/1312",
    "videocall": false,
    "memo": "★ 1차 공동구매와 묶음 배송 불가능합니다 ★\n출고 일정 : 1차 물량 모두 출고 후 / 05월 중 ~ 05월 말 예상",
    "custom": true,
    "id": "cs1774874734719"
  },
  {
    "name": "[음총] HMV (2차)",
    "distId": "dcs1774546040116",
    "country": "KR",
    "unpoPerk": "ID_PASS",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": null,
      "POCAALBUM": null,
      "ID_PASS": 24410,
      "INVENTORY": null
    },
    "purchaseStart": "2026-03-30T11:00",
    "purchaseEnd": "2026-04-07T18:00",
    "purchaseEndTxt": "",
    "defDeliveryDate": "2026-05-15",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://09platform.com/surl/P/1312",
    "videocall": false,
    "memo": "★ 1차 공동구매와 묶음 배송 불가능합니다 ★\n출고 일정 : 1차 물량 모두 출고 후 / 05월 중 ~ 05월 말 예상",
    "custom": true,
    "id": "cs1774874856715"
  },
  {
    "name": "이즈위",
    "distId": "dcs1775049442175",
    "country": "CN",
    "unpoPerk": "PHOTOBOOK",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 156,
      "POCAALBUM": 46,
      "ID_PASS": 78,
      "INVENTORY": 88
    },
    "purchaseStart": "2026-04-01T11:00",
    "purchaseEnd": "2026-04-04T22:59",
    "purchaseEndTxt": "",
    "defDeliveryDate": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://www.withfans.com/#/idolDetail?idol_id=6869",
    "videocall": true,
    "memo": "미공포가 포함되지 않은 포카앨범은 102위안\n영통 당첨자 발표: 4월 7일 18:00 (한국시간 19시)\n영통일정: 2026년 5월 9일 (정확한 시간 추후 공지)",
    "custom": true,
    "id": "cs1775049657392"
  },
  {
    "name": "[음총] WEVERSE JP",
    "distId": "dcs1774546040116",
    "country": "KR",
    "unpoPerk": "POCAALBUM",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": null,
      "POCAALBUM": 13720,
      "ID_PASS": null,
      "INVENTORY": null
    },
    "purchaseStart": "2026-04-07T11:00",
    "purchaseEnd": "2026-04-30T18:00",
    "purchaseEndTxt": "조기소진 시 마감",
    "defDeliveryDate": "2026-06-09",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://09platform.com/surl/P/1314",
    "videocall": false,
    "memo": "초동반영불가\n출고일정: 6월 말 - 7월 초",
    "custom": true,
    "id": "cs1775565948835"
  },
  {
    "name": "WEVERSE JP",
    "distId": "dcs1774619738077",
    "country": "JP",
    "unpoPerk": "POCAALBUM",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 3245,
      "POCAALBUM": 1320,
      "ID_PASS": 2420,
      "INVENTORY": 2750
    },
    "purchaseStart": "2026-04-07T11:00",
    "purchaseEnd": "",
    "purchaseEndTxt": "특전 소진시까지",
    "defDeliveryDate": "2026-06-09",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://shop.weverse.io/ko/shop/JPY/artists/167/categories/3719",
    "videocall": false,
    "memo": "포토북, ID Pass: 특전 없음 / 포카앨범: 미공포 5장\n인벤토리: 엽서 1매",
    "custom": true,
    "id": "cs1775566240225"
  },
  {
    "name": "Universal JP",
    "distId": "dcs1775566277516",
    "country": "JP",
    "unpoPerk": "PHOTOBOOK",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 3245,
      "POCAALBUM": 1320,
      "ID_PASS": null,
      "INVENTORY": 2750
    },
    "purchaseStart": "2026-04-07T11:00",
    "purchaseEnd": "",
    "purchaseEndTxt": "특전 소진시까지",
    "defDeliveryDate": "2026-06-09",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://store-annex.universal-music.co.jp/product/dsku15815/",
    "videocall": false,
    "memo": "인벤토리/포카버전 구매 시 엽서 1매 특전 증정\n포토북 구매시 미공포 증정 / 위버스재팬에서도 구매가능",
    "custom": true,
    "id": "cs1775566533743"
  },
  {
    "name": "[음총] Universal JP",
    "distId": "dcs1774546040116",
    "country": "KR",
    "unpoPerk": "PHOTOBOOK",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 32740,
      "POCAALBUM": null,
      "ID_PASS": null,
      "INVENTORY": null
    },
    "purchaseStart": "2026-04-07T11:00",
    "purchaseEnd": "2026-04-11T23:59",
    "purchaseEndTxt": "",
    "defDeliveryDate": "2026-06-15",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://09platform.com/product/%EA%B0%9C%EB%B3%84-%EC%98%81%ED%86%B5-%EC%9D%91%EB%AA%A8-%EB%B6%88%EA%B0%80-%EC%9D%BC%EB%B3%B8%EC%83%B5-%ED%8A%B9%EC%A0%84-%EC%9C%A0%EB%8B%88%EB%B2%84%EC%84%A4-%ED%94%8C%EB%A0%88%EC%9D%B4%EB%B8%8C-%EC%9D%8C%EC%9B%90%EC%B4%9D%EA%B3%B5%ED%8C%80-%ED%94%8C%EB%A0%88%EC%9D%B4%EB%B8%8C-plave-4th-mini-album-caligo-pt/1315/category/1/display/3/?icid=MAIN.product_listmain_2",
    "videocall": false,
    "memo": "",
    "custom": true,
    "id": "cs1775737339629"
  },
  {
    "name": "케타포",
    "distId": "dcs1774619329527",
    "country": "KR",
    "unpoPerk": "POCAALBUM",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": null,
      "POCAALBUM": 8200,
      "ID_PASS": null,
      "INVENTORY": null
    },
    "purchaseStart": "2026-04-14T11:00",
    "purchaseEnd": "2026-04-20T20:00",
    "purchaseEndTxt": "",
    "defDeliveryDate": "",
    "offlineStart": "2026-04-14",
    "offlineEnd": "2026-04-20",
    "offlineHours": "11:00 - 20:00 (15-16시 브레이크)",
    "offlineAddress": "케타포 인사 / 케타포 코엑스",
    "offlineNote": "포카앨범 구매 시 미공포\n스페셜메뉴 구매 시 컨셉포토카드 중 랜덤 1종 + 로고스티커 1종\n네임스티커",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://kr.ktown4u.com/iteminfo?goods_no=159360",
    "videocall": false,
    "memo": "",
    "custom": true,
    "id": "cs1775737775955"
  },
  {
    "name": "위드뮤",
    "distId": "dcs1776084976682",
    "country": "KR",
    "unpoPerk": "INVENTORY",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": null,
      "POCAALBUM": null,
      "ID_PASS": null,
      "INVENTORY": 17100
    },
    "purchaseStart": "2026-04-13T11:00",
    "purchaseEnd": "2026-04-16T23:59",
    "purchaseEndTxt": "",
    "defDeliveryDate": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://withmuu.com/goods/event_sale.php?sno=1333",
    "videocall": true,
    "memo": "영통응모 발표 4/17 2시",
    "custom": true,
    "id": "cs1776085066455"
  },
  {
    "name": "Youtube",
    "distId": "dcs1776085087300",
    "country": "KR",
    "unpoPerk": "POCAALBUM",
    "priceMode": "custom",
    "customPrices": {
      "PHOTOBOOK": 20000,
      "POCAALBUM": 8200,
      "ID_PASS": 14900,
      "INVENTORY": 17100
    },
    "purchaseStart": "2026-04-13T18:00",
    "purchaseEnd": "2026-04-20T23:00",
    "purchaseEndTxt": "",
    "defDeliveryDate": "",
    "offlineStart": "",
    "offlineEnd": "",
    "offlineHours": "",
    "offlineAddress": "",
    "offlineNote": "",
    "offlineLuckyDraw": false,
    "defDomShip": 0,
    "defOvsShip": 0,
    "url": "https://www.youtube.com/@plave_official/store",
    "videocall": true,
    "memo": "",
    "custom": true,
    "id": "cs1776085185495"
  }
];

// 멀티세트 그룹 (세트가 2개 이상인 판매처)
// { section: { storeName: setCount } }
var UNPO_MULTI_SETS = {
  "ID_PASS": {
    "무신사": 2,
    "Hello82": 2
  },
  "POCAALBUM": {
    "케타포": 2,
    "Youtube": 1
  },
  "INVENTORY": {
    "위드뮤": 1
  },
  "PHOTOBOOK": {
    "TME": 2
  }
};

// 이미지 공유 그룹 (같은 미공포 이미지를 여러 판매처가 공유하는 경우)
var UNPO_SHARED_GROUPS = {
  "ASTERUM_433": {
    "label": "ASTERUM 433-10 (십카페럭드)",
    "stores": [
      {
        "section": "ID_PASS",
        "store": "무신사",
        "setIdx": 1
      },
      {
        "section": "POCAALBUM",
        "store": "길보드",
        "setIdx": 0
      }
    ]
  }
};


// ─── 앨범 종류 ───────────────────────────────
var ALBUMS = [
  {k:'PHOTOBOOK', lb:'PHOTOBOOK'},
  {k:'POCAALBUM', lb:'POCAALBUM'},
  {k:'ID_PASS',  lb:'ID PASS'},
  {k:'INVENTORY',lb:'INVENTORY'},
];
var COUNTRIES = {
  KR:{lb:'🇰🇷 한국', cur:'KRW', ovs:false},
  JP:{lb:'🇯🇵 일본', cur:'JPY', ovs:true},
  CN:{lb:'🇨🇳 중국', cur:'CNY', ovs:true},
  TW:{lb:'🇹🇼 대만', cur:'TWD', ovs:true},
  US:{lb:'🇺🇸 미국', cur:'USD', ovs:true},
  OTHER:{lb:'🌐 기타', cur:'OTHER', ovs:true},
};
var STATUSES = [
  {k:'none',   lb:'미구매',   cls:'bx-none'},
  {k:'waiting',lb:'구매대기', cls:'bx-wait'},
  {k:'ordered',lb:'구매완료', cls:'bx-ord'},
  {k:'delivered',lb:'배송완료',cls:'bx-del'},
];
var PRICES = {"KR": {"PHOTOBOOK": 20000, "POCAALBUM": 8200, "ID_PASS": 14900, "INVENTORY": 17100}, "JP": {"PHOTOBOOK": null, "POCAALBUM": null, "ID_PASS": 2420, "INVENTORY": null}, "CN": {"PHOTOBOOK": 96, "POCAALBUM": null, "ID_PASS": null, "INVENTORY": null}, "TW": {"PHOTOBOOK": null, "POCAALBUM": 210, "ID_PASS": null, "INVENTORY": null}, "US": {"PHOTOBOOK": null, "POCAALBUM": null, "ID_PASS": 29.98, "INVENTORY": null}, "OTHER": {"PHOTOBOOK": null, "POCAALBUM": null, "ID_PASS": null, "INVENTORY": null}};
var DEF_RATES = {JPY:9.429, CNY:217.5556, USD:1504.0284, TWD:47.0702, OTHER:1};

// ═══════════════════════════════════════════
// INITIAL STORE DATA
// ═══════════════════════════════════════════

// ─── 스케줄 ──────────────────────────────────
var SCHEDULE = [
  {date:'2026-03-30', label:'컨셉포토 B 공개', key:true},
  {date:'2026-04-02', label:'비주얼 샘플러 B 공개', key:true},
  {date:'2026-04-06', label:'트랙리스트 공개', key:true},
  {date:'2026-04-07', label:'실물 앨범 프리뷰', key:true},
  {date:'2026-04-08', label:'하이라이트 메들리', key:true},
  {date:'2026-04-10', label:'뮤직비디오 티저 공개', key:true},
  {date:'2026-04-13', label:'Caligo Pt.2 MV 공개 & 디지털 발매', key:true, important:true, time:'오후 6시 KST'},
  {date:'2026-04-14', label:'Caligo Pt.2 앨범 발매', key:true, important:true},
];


// ── CHARACTER IMAGES ──

// ─── 이미지 공유 그룹 (같은 미공포를 공유하는 판매처) ───
var UNPO_SHARED = [
  {ak:'POCAALBUM', bn:'길보드',    sharedWith:{ak:'ID_PASS',   bn:'무신사'}},
];
